import opentype from "opentype.js";

export type PixelizeOptions = {
  pixelsPerEm: number;
  threshold: number;
  expand: number;
  shiftX?: number;
  shiftY?: number;
};

export type FontMetrics = {
  unitsPerEm: number;
  ascender: number;
  descender: number;
};

export type CellMask = {
  cols: number;
  rows: number;
  cells: Uint8Array;
};

export type CoverageItem = {
  codePoint: number;
  char: string;
  supported: boolean;
};

export type PixelizeResult = {
  font: opentype.Font;
  arrayBuffer: ArrayBuffer;
  glyphCount: number;
  familyName: string;
};

const BASIC_LATIN_START = 32;
const BASIC_LATIN_END = 126;
const DERIVATIVE_FAMILY_NAME = "Pixelplease Test";
const DERIVATIVE_STYLE_NAME = "Regular";
const DERIVATIVE_POSTSCRIPT_NAME = "PixelpleaseTest-Regular";
const MIN_PIXELS_PER_EM = 8;
const MAX_PIXELS_PER_EM = 64;

export function parseFont(buffer: ArrayBuffer): opentype.Font {
  return opentype.parse(buffer);
}

export function getFontLabel(font: opentype.Font): string {
  const family = readName(font, "preferredFamily") || readName(font, "fontFamily") || "Uploaded Font";
  const style = readName(font, "preferredSubfamily") || readName(font, "fontSubfamily") || "Regular";
  return `${family} ${style}`.trim();
}

function makeDerivativeFamilyName(): string {
  return DERIVATIVE_FAMILY_NAME;
}

export function getBasicLatinCoverage(font: opentype.Font): CoverageItem[] {
  const items: CoverageItem[] = [];

  for (let codePoint = BASIC_LATIN_START; codePoint <= BASIC_LATIN_END; codePoint += 1) {
    const char = String.fromCharCode(codePoint);
    const glyphIndex = font.charToGlyphIndex(char);
    items.push({
      codePoint,
      char,
      supported: codePoint === 32 || glyphIndex > 0,
    });
  }

  return items;
}

export async function pixelizeFont(
  sourceFont: opentype.Font,
  options: PixelizeOptions,
  onProgress?: (done: number, total: number) => void,
): Promise<PixelizeResult> {
  await nextFrame();

  const metrics = getMetrics(sourceFont);
  const familyName = makeDerivativeFamilyName();
  const glyphs: opentype.Glyph[] = [createNotDefGlyph(metrics, options)];
  const coverage = getBasicLatinCoverage(sourceFont).filter((item) => item.supported);

  for (let index = 0; index < coverage.length; index += 1) {
    const item = coverage[index];
    const glyph = sourceFont.charToGlyph(item.char);
    glyphs.push(pixelizeGlyph(glyph, item.codePoint, metrics, options));
    onProgress?.(index + 1, coverage.length);

    if (index % 12 === 0) {
      await nextFrame();
    }
  }

  const pixelFont = new opentype.Font({
    familyName,
    styleName: DERIVATIVE_STYLE_NAME,
    fullName: `${familyName} ${DERIVATIVE_STYLE_NAME}`,
    postScriptName: DERIVATIVE_POSTSCRIPT_NAME,
    unitsPerEm: metrics.unitsPerEm,
    ascender: metrics.ascender,
    descender: metrics.descender,
    manufacturer: "pixelplease",
    license:
      "Generated derivative for testing. Source font license controls use, modification, and redistribution.",
    licenseURL: "https://scripts.sil.org/OFL",
    version: "Version 0.1; generated by pixelplease",
    description:
      "Generated by pixelplease from a user-provided source font. Source family names are intentionally not reused.",
    copyright:
      "Generated by pixelplease. Source font copyright and license terms remain with the source font owner.",
    glyphs,
  });

  return {
    font: pixelFont,
    arrayBuffer: pixelFont.toArrayBuffer(),
    glyphCount: glyphs.length,
    familyName,
  };
}

function pixelizeGlyph(
  sourceGlyph: opentype.Glyph,
  codePoint: number,
  metrics: FontMetrics,
  options: PixelizeOptions,
): opentype.Glyph {
  const advanceWidth = Math.max(0, sourceGlyph.advanceWidth || metrics.unitsPerEm * 0.5);

  if (codePoint === 32 || sourceGlyph.index === 0) {
    return new opentype.Glyph({
      name: glyphName(codePoint),
      unicode: codePoint,
      advanceWidth: snapAdvance(advanceWidth, metrics, options),
      path: new opentype.Path(),
    });
  }

  const mask = rasterizeGlyphToCells(sourceGlyph, metrics, options);
  const expandedMask = options.expand > 0 ? dilateMask(mask, options.expand) : mask;
  const path = cellsToPath(expandedMask, metrics, options);

  return new opentype.Glyph({
    name: glyphName(codePoint),
    unicode: codePoint,
    advanceWidth: snapAdvance(advanceWidth, metrics, options),
    path,
  });
}

export function cellsToPath(mask: CellMask, metrics: FontMetrics, options: PixelizeOptions): opentype.Path {
  const path = new opentype.Path();
  const cellSize = getCellSize(metrics, options);

  for (let row = 0; row < mask.rows; row += 1) {
    let col = 0;

    while (col < mask.cols) {
      while (col < mask.cols && !isFilled(mask, col, row)) {
        col += 1;
      }

      if (col >= mask.cols) {
        break;
      }

      const start = col;
      while (col < mask.cols && isFilled(mask, col, row)) {
        col += 1;
      }

      const end = col;
      const x0 = start * cellSize;
      const x1 = end * cellSize;
      const yTop = metrics.ascender - row * cellSize;
      const yBottom = yTop - cellSize;
      addRect(path, x0, yBottom, x1, yTop);
    }
  }

  return path;
}

export function dilateMask(mask: CellMask, radius: number): CellMask {
  const output = new Uint8Array(mask.cells.length);

  for (let row = 0; row < mask.rows; row += 1) {
    for (let col = 0; col < mask.cols; col += 1) {
      if (!isFilled(mask, col, row)) {
        continue;
      }

      for (let y = row - radius; y <= row + radius; y += 1) {
        for (let x = col - radius; x <= col + radius; x += 1) {
          if (x >= 0 && x < mask.cols && y >= 0 && y < mask.rows) {
            output[y * mask.cols + x] = 1;
          }
        }
      }
    }
  }

  return { ...mask, cells: output };
}

function getMetrics(font: opentype.Font): FontMetrics {
  const unitsPerEm = font.unitsPerEm || 1000;
  return {
    unitsPerEm,
    ascender: font.ascender || Math.round(unitsPerEm * 0.8),
    descender: font.descender || -Math.round(unitsPerEm * 0.2),
  };
}

function getCellSize(metrics: FontMetrics, options: PixelizeOptions): number {
  return metrics.unitsPerEm / getGridPixelsPerEm(metrics, options);
}

export function getGridPixelsPerEm(metrics: FontMetrics, options: PixelizeOptions): number {
  const requested = Math.round(clamp(options.pixelsPerEm, MIN_PIXELS_PER_EM, MAX_PIXELS_PER_EM));
  const divisors: number[] = [];

  for (let divisor = MIN_PIXELS_PER_EM; divisor <= MAX_PIXELS_PER_EM; divisor += 1) {
    if (metrics.unitsPerEm % divisor === 0) {
      divisors.push(divisor);
    }
  }

  if (divisors.length === 0) {
    return requested;
  }

  return divisors.reduce((best, current) => {
    const bestDistance = Math.abs(best - requested);
    const currentDistance = Math.abs(current - requested);
    return currentDistance < bestDistance || (currentDistance === bestDistance && current > best) ? current : best;
  }, divisors[0]);
}

function rasterizeGlyphToCells(
  sourceGlyph: opentype.Glyph,
  metrics: FontMetrics,
  options: PixelizeOptions,
): CellMask {
  const cellSize = getCellSize(metrics, options);
  const advanceWidth = Math.max(cellSize, sourceGlyph.advanceWidth || metrics.unitsPerEm * 0.5);
  const cols = Math.max(1, Math.ceil(advanceWidth / cellSize));
  const rows = Math.max(1, Math.ceil((metrics.ascender - metrics.descender) / cellSize));
  const samplesPerCell = 5;
  const scale = samplesPerCell / cellSize;
  const canvas = document.createElement("canvas");
  canvas.width = cols * samplesPerCell;
  canvas.height = rows * samplesPerCell;

  const context = canvas.getContext("2d", { willReadFrequently: true });
  if (!context) {
    throw new Error("Could not create canvas context for glyph rasterization.");
  }

  const shiftX = clamp(options.shiftX ?? 0, -0.5, 0.5) * samplesPerCell;
  const shiftY = clamp(options.shiftY ?? 0, -0.5, 0.5) * samplesPerCell;

  context.clearRect(0, 0, canvas.width, canvas.height);
  context.fillStyle = "#000";
  sourceGlyph.draw(context, shiftX, metrics.ascender * scale + shiftY, metrics.unitsPerEm * scale);

  const data = context.getImageData(0, 0, canvas.width, canvas.height).data;
  const cells = new Uint8Array(cols * rows);
  const threshold = clamp(options.threshold, 0.05, 0.95);

  for (let row = 0; row < rows; row += 1) {
    for (let col = 0; col < cols; col += 1) {
      let alphaTotal = 0;

      for (let y = 0; y < samplesPerCell; y += 1) {
        for (let x = 0; x < samplesPerCell; x += 1) {
          const pixelX = col * samplesPerCell + x;
          const pixelY = row * samplesPerCell + y;
          const alphaIndex = (pixelY * canvas.width + pixelX) * 4 + 3;
          alphaTotal += data[alphaIndex];
        }
      }

      const fillRatio = alphaTotal / (255 * samplesPerCell * samplesPerCell);
      cells[row * cols + col] = fillRatio >= threshold ? 1 : 0;
    }
  }

  return { cols, rows, cells };
}

function createNotDefGlyph(metrics: FontMetrics, options: PixelizeOptions): opentype.Glyph {
  const cellSize = getCellSize(metrics, options);
  const path = new opentype.Path();
  const width = Math.round(metrics.unitsPerEm * 0.5 / cellSize) * cellSize;
  const top = Math.round(metrics.ascender / cellSize) * cellSize;
  const bottom = Math.round(metrics.descender / cellSize) * cellSize;

  addRect(path, 0, bottom, width, top);
  addRect(path, cellSize, bottom + cellSize, width - cellSize, top - cellSize, true);

  return new opentype.Glyph({
    name: ".notdef",
    advanceWidth: width + cellSize,
    path,
  });
}

function addRect(path: opentype.Path, x0: number, y0: number, x1: number, y1: number, reverse = false): void {
  if (reverse) {
    path.moveTo(x0, y0);
    path.lineTo(x0, y1);
    path.lineTo(x1, y1);
    path.lineTo(x1, y0);
    path.close();
    return;
  }

  path.moveTo(x0, y0);
  path.lineTo(x1, y0);
  path.lineTo(x1, y1);
  path.lineTo(x0, y1);
  path.close();
}

function isFilled(mask: CellMask, col: number, row: number): boolean {
  return mask.cells[row * mask.cols + col] === 1;
}

function snapAdvance(advanceWidth: number, metrics: FontMetrics, options: PixelizeOptions): number {
  const cellSize = getCellSize(metrics, options);
  return Math.max(cellSize, Math.ceil(advanceWidth / cellSize) * cellSize);
}

function glyphName(codePoint: number): string {
  return `u${codePoint.toString(16).toUpperCase().padStart(4, "0")}`;
}

function readName(font: opentype.Font, key: string): string | undefined {
  const names = font.names as unknown as Record<string, Record<string, string> | undefined>;
  return names[key]?.en || Object.values(names[key] || {})[0];
}

function clamp(value: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, value));
}

function nextFrame(): Promise<void> {
  return new Promise((resolve) => requestAnimationFrame(() => resolve()));
}
