export const UI_COPY = {
  documentTitle: "pixelplease - fastest way to create a custom pixel font",
  status: {
    demoMode: "demo mode",
    generatedReady: "Generated TTF ready",
    uploadFont: "Upload a font",
    parsingFont: "Parsing font...",
    generating: "Generating...",
    pixelizingBasicLatin: "Pixelizing Basic Latin glyphs...",
    updatingPreview: "Updating preview...",
    autoGenerating: "Auto-generating...",
    error: "Error",
  },
  intro: {
    logoAriaLabel: "pixel please",
    logoParts: ["pixel", "please"],
    copy:
      "Create a pixel-style font from a regular typeface. Upload your own font or start with a Google font, tune the effect, and export as a .ttf",
  },
  sections: {
    source: "Source font and text",
    sourceMode: "Source mode",
    pixelizedPreview: "Pixelized font preview",
    demoPreview: "Pixelized demo preview",
    settings: "Settings",
  },
  sourceModes: {
    google: "Google font",
    upload: "Upload font",
  },
  source: {
    googleFontSelect: "Google Font for demo preview",
    fontOptionSeparator: " / ",
    replaceFont: "upload new font",
    sampleTextLabel: "sample text",
    sampleTextDefault:
      "Hey, this is pixelplease. I quickly pixelize fonts, adding brutal web grit and old monitor vibes to your interface 123.",
    uploadTitle: "drop a TTF/OTF here",
    licenseReminder: "Files stay in your browser. Use only fonts you have a license to edit",
  },
  controls: {
    pixelsPerEm: "pixels-per-em",
    threshold: "threshold",
    thresholdUnit: "%",
    expand: "expand",
    pixelShape: "pixel shape",
    squarePixels: "square",
    roundPixels: "round",
    shiftX: "shift-x",
    shiftY: "shift-y",
    shiftUnit: "cell",
    resetDefaults: "reset defaults",
    downloadTtf: "Download font",
    defaultDownloadName: "Pixelplease-Test.zip",
    previewSizeReadout: (size: number) => `${size} px`,
    sizeDecreaseSymbol: "−",
    sizeIncreaseSymbol: "+",
    sourceSizeGroup: "Source preview text size",
    sourceSizeDecrease: "Decrease source preview text size",
    sourceSizeIncrease: "Increase source preview text size",
    outputSizeGroup: "Pixel output preview size",
    outputSizeDecrease: "Decrease pixel output preview size",
    outputSizeIncrease: "Increase pixel output preview size",
  },
  footer: {
    ariaLabel: "Usage note",
    lines: [
      "Uploaded fonts stay in your browser.",
      "Use source fonts according to their license.",
      "Keep required copyright, license, and notice files when sharing.",
    ],
  },
  errors: {
    missingElement: (id: string) => `Missing element #${id}`,
    couldNotLoadFont: (family: string) => `Could not load ${family}.`,
    couldNotParseFont: "Could not parse this font file.",
    couldNotGenerateTtf: "Could not generate a pixelized TTF.",
  },
  dynamicStatus: {
    loadingFont: (family: string) => `Loading ${family}...`,
    generatingFrom: (label: string) => `Generating from ${label}...`,
    generatingProgress: (done: number, total: number) => `Generating ${done}/${total}`,
  },
} as const;
