export const UI_COPY = {
  documentTitle: "pixelplease",
  status: {
    demoMode: "demo mode",
    generatedReady: "Generated TTF ready",
    uploadFont: "Upload a font",
    parsingFont: "Parsing font...",
    generating: "Generating...",
    pixelizingBasicLatin: "Pixelizing Basic Latin glyphs...",
    updatingPreview: "Updating preview...",
    autoGenerating: "Auto-generating...",
    error: "Error",
  },
  intro: {
    logoAriaLabel: "pixel please",
    logoParts: ["pixel", "please"],
    copy: "Upload a font, edit sample text, preview a pixel treatment, and export a test TTF",
  },
  sections: {
    source: "Source font and text",
    sourceMode: "Source mode",
    pixelizedPreview: "Pixelized font preview",
    demoPreview: "Pixelized demo preview",
    settings: "Settings",
  },
  sourceModes: {
    google: "Google font",
    upload: "Upload font",
  },
  source: {
    googleFontSelect: "Google Font for demo preview",
    fontOptionSeparator: " / ",
    replaceFont: "upload new font",
    sampleTextLabel: "sample text",
    sampleTextDefault:
      "Hi, this is pixelplease. I quickly pixelize fonts, tweak crisp grids, and export jazzy test TTFs 123.",
    uploadTitle: "drop a TTF/OTF here",
    licenseReminder: "Please use only fonts you have a license to edit",
  },
  controls: {
    pixelsPerEm: "pixels-per-em",
    threshold: "threshold",
    thresholdUnit: "%",
    expand: "expand",
    shiftX: "shift-x",
    shiftY: "shift-y",
    shiftUnit: "cell",
    resetDefaults: "reset defaults",
    downloadTtf: "Download package",
    defaultDownloadName: "Pixelplease-Test.zip",
  },
  errors: {
    missingElement: (id: string) => `Missing element #${id}`,
    couldNotLoadFont: (family: string) => `Could not load ${family}.`,
    couldNotParseFont: "Could not parse this font file.",
    couldNotGenerateTtf: "Could not generate a pixelized TTF.",
  },
  dynamicStatus: {
    loadingFont: (family: string) => `Loading ${family}...`,
    generatingFrom: (label: string) => `Generating from ${label}...`,
    generatingProgress: (done: number, total: number) => `Generating ${done}/${total}`,
  },
} as const;
